# build environment
FROM node:16.19.0-alpine as build
WORKDIR /app
ENV PATH /node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install

COPY . /app
RUN npm run build

# production environment
FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]