FROM maven AS build
WORKDIR /cdc-test-app
COPY pom.xml ./pom.xml
COPY ./app/pom.xml ./app/pom.xml
RUN mvn -f pom.xml dependency:go-offline -B
COPY . .
RUN mvn -f pom.xml clean package -Dmaven.test.skip -DskipTests -T 4C

FROM openjdk:17-alpine3.14
COPY --from=build /cdc-test-app/app/target/contracts-tests-admin.jar /contracts-tests-admin.jar
ENTRYPOINT ["java","-jar","/contracts-tests-admin.jar"]