FROM maven AS build
WORKDIR /cdc-test-app
COPY . .
RUN mvn -f pom.xml clean package -T 4C

FROM eclipse-temurin:17-jdk
COPY --from=build /cdc-test-app/app/target/contracts-tests-admin.jar /contracts-tests-admin.jar
ENTRYPOINT ["java","-jar","/contracts-tests-admin.jar"]
