version: '2.4'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "contracts_tests_db"
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres:/var/lib/postgresql/data:delegated
  contracts-tests-admin:
    mem_limit: 1000m
    container_name: contracts-tests-admin
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8085:8085"
    depends_on:
      - postgres
  front-admin:
    container_name: front-admin
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"

volumes:
  postgres:
