version: '2.4'

services:
  contracts-tests-admin:
    mem_limit: 1000m
    container_name: contracts-tests-admin
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "8085:8085"
  front-admin:
    container_name: front-admin
    build:
      context: ./frontend
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: hhtech
      MINIO_ROOT_PASSWORD: hhtech123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  minio-storage:
