version: '2.4'

services:
  contracts-test-admin:
    mem_limit: 1000m
    container_name: contracts-tests-admin
    build:
      context: ./app
      dockerfile: ./DockerFile
    ports:
      - "8085:8085"
  front-admin:
    container_name: front-admin
    build:
      context: ./fronted
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"