FROM eclipse-temurin:17-alpine
MAINTAINER hh.com
ARG APP_DIR=/opt/contract-test-admin
WORKDIR ${APP_DIR}
COPY target/contracts-tests-admin.jar ${APP_DIR}/contracts-tests-admin.jar
ENTRYPOINT ["java","-jar","contracts-tests-admin.jar"]
